### ISSUE TITLE
Items with 'The' in name get it removed when parsed.

### ISSUE THREAD

**Issue by danocmx** [danocmx/node-tf2-item-format#15]
Demonstration item:  `The Bitter Taste of Defeat and Lime`
Expected response: `{ name: 'The Bitter Taste of Defeat and Lime', quality: 6 }`
Current response: `{ name: 'Bitter Taste of Defeat and Lime', quality: 6 }`

Procedure:
- [x] get alls item with The from schema
- [x] make exceptions for it
- [x] write tests

**Comment by Niaz-Ul-Haque** [comment]
Very interested in working with this issue, as open sourcing is a part of my coursework and self prctice. Please assigned me this issue and ill try my best to come with best possible solution. Thank you!

**Comment by danocmx** [comment]
> 
> 
> Very interested in working with this issue, as open sourcing is a part of my coursework and self prctice. Please assigned me this issue and ill try my best to come with best possible solution. Thank you!
Already working on a solution.

**Comment by Niaz-Ul-Haque** [comment]
Oh I see, good luck then.
