### ISSUE TITLE
[Bug] Incorrect names of items with proper_name property

### ISSUE THREAD

**Issue by piman51277** [danocmx/node-tf2-item-format#177]
#  Bug description
Certain items in Tf2, such as "The Blutsauger", "The Anger", etc. have a "The" prefixed when in Unique form. 
When stringifying the SKUs of such items, the "The" is omitted.
Example: 
```javascript
const { stringify, parseSKU } = require("tf2-item-format/static");
console.log(stringify(parseSKU("36;6"))); //returns "Blutsauger", should be "The Blutsauger"
```

# Examples of affected items
**This bug currently affects over 1,200 items** 

- The Blutsauger
  - [Backpack.tf link](https://backpack.tf/stats/Unique/Blutsauger/Tradable/Craftable)
- The Warrior's Spirit
  - [Backpack.tf link](https://backpack.tf/stats/Unique/Warrior%27s%20Spirit/Tradable/Craftable)
- The Hair of the Dog
  - [Backpack.tf link](https://backpack.tf/stats/Unique/Hair%20of%20the%20Dog/Tradable/Craftable)

# Why this matters
Sites such as Backpack.tf respect the "The" prefix, and this module is currently incompatible with their _more correct_ schema system.

# Origin of the Bug
This bug originates within a dependency, [node-tf2-static-schema](https://github.com/danocmx/node-tf2-static-schema). Specifically, the [item-names.json](https://github.com/danocmx/node-tf2-static-schema/blob/master/static/item-names.json) file. `tf2-item-format` blindly trusts this file to resolve SKUs to item names.  _However, this bug cannot be blamed on tf2-static-schema, as they are providing the correct base name of the item, which is correct in most contexts_

# Proposed solution
Luckily, the method to find which item names have this prefix is quite simple. Items with the `proper_name` property set to `true` within the raw tf2 schema _should_ have the "The" prefix when unique. 
- [Tf2 wiki](https://wiki.teamfortress.com/wiki/WebAPI/GetSchema#Result_Data)
- [Typed Schema](https://gist.github.com/piman51277/3cbe16519c9e89ec8335dc7230090de6)

> However, the `name` property **does not always include the "The" prefix** when the prefix is still required. For example, the "The Sun-on-a-Stick" has the `name` property set to "Sun-on-a-Stick".

In order to keep backwards compatibilty with existing systems, I propose that this fix should be implemented as a separate function, or as an option to the `stringify` function.

**Comment by piman51277** [comment]
I have made a rudimentary fix via [this](https://www.npmjs.com/package/backpack-name) module on npm.

**Comment by danocmx** [comment]
I know the documentation is not up to date because of lack of time. But this issue has already been solved by [enabling flag](https://github.com/danocmx/node-tf2-item-format/blob/master/src/stringify.ts#L17-L19) in `stringify`. Example `stringify(parseSKU("36;6", { determineUniqueHat: true }))`. It's not a default option because it would break existing apps.
