### ISSUE TITLE
Add overload to `stringify` to accept sku string

### ISSUE THREAD

**Issue by prenaissance** [danocmx/node-tf2-item-format#254]
## Proposal

Add an overload to `stringify` to directly get the item name from the SKU. In my opinion, this would make the api simpler and it's a common operation (at least for my use case).

Example:
```ts
const name = stringify("211;11;australium;kt-3;festive");
console.log(name); // "Strange Festivized Professional Killstreak Australium Medi Gun"
```

## Current usage

```ts
const attributes = parseSKU("211;11;australium;kt-3;festive");
const name = stringify(attributes);
```

If you're happy with that, I can open a PR.

**Comment by danocmx** [comment]
Sounds like a good change, you can open a PR, if you are still interested.
